layout_spectrum: 0.9991384
typography_spectrum: 0.5062116
color:
  saturation: 0.7095928
  lightness: 0.5733072
  brandStrength: 0.8688045
  rhythmicContrast: 0.5870569
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Turtle Giant2
